//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdleFactory {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdleFactory.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string action_area {
            get {
                return ResourceManager.GetString("action_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chop Trees.
        /// </summary>
        internal static string action_chop {
            get {
                return ResourceManager.GetString("action.chop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mining.
        /// </summary>
        internal static string action_mine {
            get {
                return ResourceManager.GetString("action.mine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buildings.
        /// </summary>
        internal static string building_area {
            get {
                return ResourceManager.GetString("building_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A primitive furnace. You could do some low-tech smelting here..
        /// </summary>
        internal static string building_furnace_description {
            get {
                return ResourceManager.GetString("building.furnace.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe is used for transport items and fluid.
        /// </summary>
        internal static string building_pipe_description {
            get {
                return ResourceManager.GetString("building.pipe.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic workbench. You could do some simple job here..
        /// </summary>
        internal static string building_workbench_description {
            get {
                return ResourceManager.GetString("building.workbench.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string culture {
            get {
                return ResourceManager.GetString("culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        internal static string exchange_area {
            get {
                return ResourceManager.GetString("exchange_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home_area {
            get {
                return ResourceManager.GetString("home_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charcoal.
        /// </summary>
        internal static string item_charcoal {
            get {
                return ResourceManager.GetString("item.charcoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furnace.
        /// </summary>
        internal static string item_furnace {
            get {
                return ResourceManager.GetString("item.furnace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron Ore.
        /// </summary>
        internal static string item_ironOre {
            get {
                return ResourceManager.GetString("item.ironOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe.
        /// </summary>
        internal static string item_pipe {
            get {
                return ResourceManager.GetString("item.pipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone.
        /// </summary>
        internal static string item_stone {
            get {
                return ResourceManager.GetString("item.stone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood Log.
        /// </summary>
        internal static string item_woodlog {
            get {
                return ResourceManager.GetString("item.woodlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Bench.
        /// </summary>
        internal static string item_workbench {
            get {
                return ResourceManager.GetString("item.workbench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} builds a {1}.
        /// </summary>
        internal static string notify_build {
            get {
                return ResourceManager.GetString("notify.build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} retrieves building of {1}.
        /// </summary>
        internal static string notify_buildingRetrieve {
            get {
                return ResourceManager.GetString("notify.buildingRetrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gets {1} of {2}..
        /// </summary>
        internal static string notify_getRes {
            get {
                return ResourceManager.GetString("notify.getRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string notify_history {
            get {
                return ResourceManager.GetString("notify_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string str_add {
            get {
                return ResourceManager.GetString("str.add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string str_back {
            get {
                return ResourceManager.GetString("str.back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string str_build {
            get {
                return ResourceManager.GetString("str.build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buildings.
        /// </summary>
        internal static string str_building {
            get {
                return ResourceManager.GetString("str.building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Detail.
        /// </summary>
        internal static string str_buildingDetail {
            get {
                return ResourceManager.GetString("str.buildingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrive.
        /// </summary>
        internal static string str_buildingRetrieve {
            get {
                return ResourceManager.GetString("str.buildingRetrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafting.
        /// </summary>
        internal static string str_crafting {
            get {
                return ResourceManager.GetString("str.crafting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string str_enable {
            get {
                return ResourceManager.GetString("str.enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract from input.
        /// </summary>
        internal static string str_extractFromInput {
            get {
                return ResourceManager.GetString("str.extractFromInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string str_filter {
            get {
                return ResourceManager.GetString("str.filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        internal static string str_fuel {
            get {
                return ResourceManager.GetString("str.fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string str_input {
            get {
                return ResourceManager.GetString("str.input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network ID.
        /// </summary>
        internal static string str_networkID {
            get {
                return ResourceManager.GetString("str.networkID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network members.
        /// </summary>
        internal static string str_networkMembers {
            get {
                return ResourceManager.GetString("str.networkMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network nodes.
        /// </summary>
        internal static string str_networkNodes {
            get {
                return ResourceManager.GetString("str.networkNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        internal static string str_nickName {
            get {
                return ResourceManager.GetString("str.nickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string str_output {
            get {
                return ResourceManager.GetString("str.output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe actions.
        /// </summary>
        internal static string str_pipeActions {
            get {
                return ResourceManager.GetString("str.pipeActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This pipe connects to.
        /// </summary>
        internal static string str_pipeConnectNeighbor {
            get {
                return ResourceManager.GetString("str.pipeConnectNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string str_progress {
            get {
                return ResourceManager.GetString("str.progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make {0} using {1}.
        /// </summary>
        internal static string str_recipeDetail {
            get {
                return ResourceManager.GetString("str.recipeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel value remaining.
        /// </summary>
        internal static string str_remainFuelValue {
            get {
                return ResourceManager.GetString("str.remainFuelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string str_remove {
            get {
                return ResourceManager.GetString("str.remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string str_resources {
            get {
                return ResourceManager.GetString("str.resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select recipe.
        /// </summary>
        internal static string str_selectRecipe {
            get {
                return ResourceManager.GetString("str.selectRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to.
        /// </summary>
        internal static string str_sendTo {
            get {
                return ResourceManager.GetString("str.sendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Grid Border.
        /// </summary>
        internal static string str_showGrid {
            get {
                return ResourceManager.GetString("str.showGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show related.
        /// </summary>
        internal static string str_showRelatedPipeAction {
            get {
                return ResourceManager.GetString("str.showRelatedPipeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken from.
        /// </summary>
        internal static string str_takeFrom {
            get {
                return ResourceManager.GetString("str.takeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string str_temperature {
            get {
                return ResourceManager.GetString("str.temperature", resourceCulture);
            }
        }
    }
}
